import { Component } from '@angular/core';
import { NgFor } from '@angular/common';

@Component({
    selector: 'app-mt940',
    templateUrl: './mt940.component.html',
    styleUrls: ['./mt940.component.css'],
    standalone: true,
    imports: [NgFor]
})
export class Mt940Component {

  data = [
    {
      "accountNumber": "601320369201",
      "fileName": "e-Statement SWIFT MT940 - Sept 1 to Dec 6 2022.txt",
      "parseStatus": true,
      "statementList": [
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-02T00:00:00.000+00:00",
          "openingBalance": 4368.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00201",
          "transactionReferenceNumber": "2209020010181388",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-09-02T00:00:00.000+00:00",
              "entryDate": "02 September",
              "creditDebit": "D",
              "amount": 2210.0,
              "transactionCode": "N",
              "referenceOwner": "CONSULTANT PAYME",
              "referenceInstitution": "CT0026096757M001",
              "cs2": null,
              "supplementaryDetails": "CONSULTANT PAYME",
              "statementLine": "2209020902D2210,NMSCCONSULTANT PAYME//CT0026096757M001"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-03T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00202",
          "transactionReferenceNumber": "2209030010177022",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-05T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00203",
          "transactionReferenceNumber": "2209050010193197",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-06T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00204",
          "transactionReferenceNumber": "2209060010181922",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-07T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00205",
          "transactionReferenceNumber": "2209070010180414",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-08T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00206",
          "transactionReferenceNumber": "2209080010179733",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-09T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00207",
          "transactionReferenceNumber": "2209090010185859",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-10T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00208",
          "transactionReferenceNumber": "2209100010176226",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-12T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00209",
          "transactionReferenceNumber": "2209120010190413",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-13T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00210",
          "transactionReferenceNumber": "2209130010179027",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-14T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00211",
          "transactionReferenceNumber": "2209140010179518",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-15T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00212",
          "transactionReferenceNumber": "2209150010180179",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-16T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00213",
          "transactionReferenceNumber": "2209160010179544",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-17T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2158.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00214",
          "transactionReferenceNumber": "2209170010175567",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-19T00:00:00.000+00:00",
          "openingBalance": 2158.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00215",
          "transactionReferenceNumber": "2209190010189767",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-09-19T00:00:00.000+00:00",
              "entryDate": "19 September",
              "creditDebit": "D",
              "amount": 86.0,
              "transactionCode": "N",
              "referenceOwner": "Txn Charges Bill",
              "referenceInstitution": "0000001036880991",
              "cs2": null,
              "supplementaryDetails": "Txn Charges Bill",
              "statementLine": "2209190919D86,NMSCTxn Charges Bill//0000001036880991"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-20T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00216",
          "transactionReferenceNumber": "2209200010179493",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-21T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00217",
          "transactionReferenceNumber": "2209210010178358",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-22T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00218",
          "transactionReferenceNumber": "2209220010178138",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-23T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00219",
          "transactionReferenceNumber": "2209230010180063",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-24T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00220",
          "transactionReferenceNumber": "2209240010175198",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-26T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00221",
          "transactionReferenceNumber": "2209260010189452",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-27T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00222",
          "transactionReferenceNumber": "2209270010179910",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-28T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00223",
          "transactionReferenceNumber": "2209280010180568",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-29T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00224",
          "transactionReferenceNumber": "2209290010180727",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-30T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00225",
          "transactionReferenceNumber": "2209300010183193",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-01T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 2072.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00226",
          "transactionReferenceNumber": "2210010010177259",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-03T00:00:00.000+00:00",
          "openingBalance": 2072.53,
          "closingBalance": 566.73,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00227",
          "transactionReferenceNumber": "2210030010193699",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-10-03T00:00:00.000+00:00",
              "entryDate": "03 October",
              "creditDebit": "D",
              "amount": 1505.8,
              "transactionCode": "N",
              "referenceOwner": "277150160264",
              "referenceInstitution": "CT0026383124M001",
              "cs2": null,
              "supplementaryDetails": "277150160264",
              "statementLine": "2210031003D1505,8NMSC277150160264//CT0026383124M001"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-04T00:00:00.000+00:00",
          "openingBalance": 566.73,
          "closingBalance": 523.73,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00228",
          "transactionReferenceNumber": "2210040010179437",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-10-04T00:00:00.000+00:00",
              "entryDate": "04 October",
              "creditDebit": "D",
              "amount": 43.0,
              "transactionCode": "N",
              "referenceOwner": "Txn Charges Bill",
              "referenceInstitution": "0000001037191582",
              "cs2": null,
              "supplementaryDetails": "Txn Charges Bill",
              "statementLine": "2210041004D43,NMSCTxn Charges Bill//0000001037191582"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-05T00:00:00.000+00:00",
          "openingBalance": 523.73,
          "closingBalance": 523.73,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00229",
          "transactionReferenceNumber": "2210050010179904",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-06T00:00:00.000+00:00",
          "openingBalance": 523.73,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00230",
          "transactionReferenceNumber": "2210060010179104",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-10-06T00:00:00.000+00:00",
              "entryDate": "06 October",
              "creditDebit": "D",
              "amount": 21.25,
              "transactionCode": "N",
              "referenceOwner": "SVC CHARGE BRL",
              "referenceInstitution": "BRL-84",
              "cs2": null,
              "supplementaryDetails": "SVC CHARGE BRL",
              "statementLine": "2210061006D21,25NMSCSVC CHARGE BRL//BRL-84"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-07T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00231",
          "transactionReferenceNumber": "2210070010179509",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-08T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00232",
          "transactionReferenceNumber": "2210080010175492",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-10T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00233",
          "transactionReferenceNumber": "2210100010189100",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-11T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00234",
          "transactionReferenceNumber": "2210110010178285",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-12T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00235",
          "transactionReferenceNumber": "2210120010178077",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-13T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00236",
          "transactionReferenceNumber": "2210130010177867",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-14T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00237",
          "transactionReferenceNumber": "2210140010179261",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-15T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 502.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00238",
          "transactionReferenceNumber": "2210150010174802",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-17T00:00:00.000+00:00",
          "openingBalance": 502.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00239",
          "transactionReferenceNumber": "2210170010188998",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-10-17T00:00:00.000+00:00",
              "entryDate": "17 October",
              "creditDebit": "C",
              "amount": 1425.0,
              "transactionCode": "N",
              "referenceOwner": "CT0025834431 RTN",
              "referenceInstitution": "INVALID BENE ACC",
              "cs2": null,
              "supplementaryDetails": "CT0025834431 RTN",
              "statementLine": "2210171017C1425,NMSCCT0025834431 RTN//INVALID BENE ACC"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-18T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00240",
          "transactionReferenceNumber": "2210180010178247",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-19T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00241",
          "transactionReferenceNumber": "2210190010177082",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-20T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00242",
          "transactionReferenceNumber": "2210200010177896",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-21T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00243",
          "transactionReferenceNumber": "2210210010178339",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-22T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00244",
          "transactionReferenceNumber": "2210220010174074",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-25T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00245",
          "transactionReferenceNumber": "2210250010197209",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-26T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00246",
          "transactionReferenceNumber": "2210260010178565",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-27T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00247",
          "transactionReferenceNumber": "2210270010178156",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-28T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00248",
          "transactionReferenceNumber": "2210280010180234",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-29T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00249",
          "transactionReferenceNumber": "2210290010174963",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-10-31T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00250",
          "transactionReferenceNumber": "2210310010192564",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-01T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 1927.48,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00251",
          "transactionReferenceNumber": "2211010010182023",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-02T00:00:00.000+00:00",
          "openingBalance": 1927.48,
          "closingBalance": 215788.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00252",
          "transactionReferenceNumber": "2211020010179072",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-11-02T00:00:00.000+00:00",
              "entryDate": "02 November",
              "creditDebit": "C",
              "amount": 221250.0,
              "transactionCode": "N",
              "referenceOwner": "ACE RESOURCE ADV",
              "referenceInstitution": "6256065306FS",
              "cs2": null,
              "supplementaryDetails": "ACE RESOURCE ADV",
              "statementLine": "2211021102C221250,NMSCACE RESOURCE ADV//6256065306FS"
            },
            {
              "date": "2022-11-02T00:00:00.000+00:00",
              "entryDate": "02 November",
              "creditDebit": "D",
              "amount": 7388.7,
              "transactionCode": "N",
              "referenceOwner": "277150160264",
              "referenceInstitution": "CT0026658689M001",
              "cs2": null,
              "supplementaryDetails": "277150160264",
              "statementLine": "2211021102D7388,7NMSC277150160264//CT0026658689M001"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-03T00:00:00.000+00:00",
          "openingBalance": 215788.78,
          "closingBalance": 215788.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00253",
          "transactionReferenceNumber": "2211030010178614",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-04T00:00:00.000+00:00",
          "openingBalance": 215788.78,
          "closingBalance": 155745.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00254",
          "transactionReferenceNumber": "2211040010179569",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-11-04T00:00:00.000+00:00",
              "entryDate": "04 November",
              "creditDebit": "D",
              "amount": 60000.0,
              "transactionCode": "N",
              "referenceOwner": "INVOICE PAYMENT",
              "referenceInstitution": "CT0026675285M001",
              "cs2": null,
              "supplementaryDetails": "INVOICE PAYMENT",
              "statementLine": "2211041104D60000,NMSCINVOICE PAYMENT//CT0026675285M001"
            },
            {
              "date": "2022-11-04T00:00:00.000+00:00",
              "entryDate": "04 November",
              "creditDebit": "D",
              "amount": 43.0,
              "transactionCode": "N",
              "referenceOwner": "Txn Charges Bill",
              "referenceInstitution": "0000001037580843",
              "cs2": null,
              "supplementaryDetails": "Txn Charges Bill",
              "statementLine": "2211041104D43,NMSCTxn Charges Bill//0000001037580843"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-05T00:00:00.000+00:00",
          "openingBalance": 155745.78,
          "closingBalance": 155745.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00255",
          "transactionReferenceNumber": "2211050010174609",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-07T00:00:00.000+00:00",
          "openingBalance": 155745.78,
          "closingBalance": 155745.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00256",
          "transactionReferenceNumber": "2211070010192614",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-08T00:00:00.000+00:00",
          "openingBalance": 155745.78,
          "closingBalance": 155745.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00257",
          "transactionReferenceNumber": "2211080010177750",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-09T00:00:00.000+00:00",
          "openingBalance": 155745.78,
          "closingBalance": 155745.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00258",
          "transactionReferenceNumber": "2211090010177529",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-10T00:00:00.000+00:00",
          "openingBalance": 155745.78,
          "closingBalance": 155745.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00259",
          "transactionReferenceNumber": "2211100010178313",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-11T00:00:00.000+00:00",
          "openingBalance": 155745.78,
          "closingBalance": 155745.78,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00260",
          "transactionReferenceNumber": "2211110010178648",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-12T00:00:00.000+00:00",
          "openingBalance": 155745.78,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00261",
          "transactionReferenceNumber": "2211120010174996",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-11-12T00:00:00.000+00:00",
              "entryDate": "12 November",
              "creditDebit": "D",
              "amount": 18715.69,
              "transactionCode": "N",
              "referenceOwner": "SATGURU TRAVEL",
              "referenceInstitution": "CT0026747367",
              "cs2": null,
              "supplementaryDetails": "SATGURU TRAVEL",
              "statementLine": "2211121112D18715,69NMSCSATGURU TRAVEL//CT0026747367"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-14T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00262",
          "transactionReferenceNumber": "2211140010190815",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-15T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00263",
          "transactionReferenceNumber": "2211150010177963",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-16T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00264",
          "transactionReferenceNumber": "2211160010176907",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-17T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00265",
          "transactionReferenceNumber": "2211170010176871",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-18T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00266",
          "transactionReferenceNumber": "2211180010177494",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-19T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00267",
          "transactionReferenceNumber": "2211190010172925",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-21T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00268",
          "transactionReferenceNumber": "2211210010187641",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-22T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00269",
          "transactionReferenceNumber": "2211220010176875",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-23T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00270",
          "transactionReferenceNumber": "2211230010176646",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-24T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 137030.09,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00271",
          "transactionReferenceNumber": "2211240010177410",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-25T00:00:00.000+00:00",
          "openingBalance": 137030.09,
          "closingBalance": 126897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00272",
          "transactionReferenceNumber": "2211250010179847",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-11-25T00:00:00.000+00:00",
              "entryDate": "25 November",
              "creditDebit": "C",
              "amount": 6103.8,
              "transactionCode": "N",
              "referenceOwner": "PACIFIC INTER-LI",
              "referenceInstitution": "C0023273350701",
              "cs2": null,
              "supplementaryDetails": "PACIFIC INTER-LI",
              "statementLine": "2211251125C6103,8NMSCPACIFIC INTER-LI//C0023273350701"
            },
            {
              "date": "2022-11-25T00:00:00.000+00:00",
              "entryDate": "25 November",
              "creditDebit": "D",
              "amount": 7.22,
              "transactionCode": "N",
              "referenceOwner": "PACIFIC INTER-LI",
              "referenceInstitution": "C0023273350701",
              "cs2": null,
              "supplementaryDetails": "PACIFIC INTER-LI",
              "statementLine": "2211251125D7,22NCHGPACIFIC INTER-LI//C0023273350701"
            },
            {
              "date": "2022-11-25T00:00:00.000+00:00",
              "entryDate": "25 November",
              "creditDebit": "D",
              "amount": 16229.0,
              "transactionCode": "N",
              "referenceOwner": "TRAVEL CONSULTIN",
              "referenceInstitution": "CT0026864786M001",
              "cs2": null,
              "supplementaryDetails": "TRAVEL CONSULTIN",
              "statementLine": "2211251125D16229,NMSCTRAVEL CONSULTIN//CT0026864786M001"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-26T00:00:00.000+00:00",
          "openingBalance": 126897.67,
          "closingBalance": 126897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00273",
          "transactionReferenceNumber": "2211260010174083",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-28T00:00:00.000+00:00",
          "openingBalance": 126897.67,
          "closingBalance": 126897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00274",
          "transactionReferenceNumber": "2211280010190868",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-29T00:00:00.000+00:00",
          "openingBalance": 126897.67,
          "closingBalance": 126897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00275",
          "transactionReferenceNumber": "2211290010179513",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-11-30T00:00:00.000+00:00",
          "openingBalance": 126897.67,
          "closingBalance": 126897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00276",
          "transactionReferenceNumber": "2211300010180832",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-01T00:00:00.000+00:00",
          "openingBalance": 126897.67,
          "closingBalance": 126897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00277",
          "transactionReferenceNumber": "2212010010181731",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-02T00:00:00.000+00:00",
          "openingBalance": 126897.67,
          "closingBalance": 96897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00278",
          "transactionReferenceNumber": "2212020010178989",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-12-02T00:00:00.000+00:00",
              "entryDate": "02 December",
              "creditDebit": "D",
              "amount": 30000.0,
              "transactionCode": "N",
              "referenceOwner": "EmployeeS Expense",
              "referenceInstitution": "CT0026937956M001",
              "cs2": null,
              "supplementaryDetails": "EmployeeS Expense",
              "statementLine": "2212021202D30000,NMSCEmployeeS Expense//CT0026937956M001"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-03T00:00:00.000+00:00",
          "openingBalance": 96897.67,
          "closingBalance": 96897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00279",
          "transactionReferenceNumber": "2212030010173545",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-05T00:00:00.000+00:00",
          "openingBalance": 96897.67,
          "closingBalance": 96768.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00280",
          "transactionReferenceNumber": "2212050010190168",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-12-05T00:00:00.000+00:00",
              "entryDate": "05 December",
              "creditDebit": "D",
              "amount": 129.0,
              "transactionCode": "N",
              "referenceOwner": "Txn Charges Bill",
              "referenceInstitution": "0000001037970431",
              "cs2": null,
              "supplementaryDetails": "Txn Charges Bill",
              "statementLine": "2212051205D129,NMSCTxn Charges Bill//0000001037970431"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-06T00:00:00.000+00:00",
          "openingBalance": 96768.67,
          "closingBalance": 96768.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00281",
          "transactionReferenceNumber": "2212060010177354",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-09-01T00:00:00.000+00:00",
          "openingBalance": 4368.53,
          "closingBalance": 4368.53,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00200",
          "transactionReferenceNumber": "2209010010183986",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        }
      ]
    },
    {
      "accountNumber": "601320369201",
      "fileName": "e-Statement SWIFT MT940 - Dec 1 to Dec 6 2022.txt",
      "parseStatus": true,
      "statementList": [
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-02T00:00:00.000+00:00",
          "openingBalance": 126897.67,
          "closingBalance": 96897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00278",
          "transactionReferenceNumber": "2212020010178989",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-12-02T00:00:00.000+00:00",
              "entryDate": "02 December",
              "creditDebit": "D",
              "amount": 30000.0,
              "transactionCode": "N",
              "referenceOwner": "DIRECTORS Expense",
              "referenceInstitution": "CT0026937956M001",
              "cs2": null,
              "supplementaryDetails": "DIRECTORS Expense",
              "statementLine": "2212021202D30000,NMSCDIRECTORS Expense//CT0026937956M001"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-03T00:00:00.000+00:00",
          "openingBalance": 96897.67,
          "closingBalance": 96897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00279",
          "transactionReferenceNumber": "2212030010173545",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-05T00:00:00.000+00:00",
          "openingBalance": 96897.67,
          "closingBalance": 96768.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00280",
          "transactionReferenceNumber": "2212050010190168",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": [
            {
              "date": "2022-12-05T00:00:00.000+00:00",
              "entryDate": "05 December",
              "creditDebit": "D",
              "amount": 129.0,
              "transactionCode": "N",
              "referenceOwner": "Txn Charges Bill",
              "referenceInstitution": "0000001037970431",
              "cs2": null,
              "supplementaryDetails": "Txn Charges Bill",
              "statementLine": "2212051205D129,NMSCTxn Charges Bill//0000001037970431"
            }
          ]
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-06T00:00:00.000+00:00",
          "openingBalance": 96768.67,
          "closingBalance": 96768.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00281",
          "transactionReferenceNumber": "2212060010177354",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        },
        {
          "username": null,
          "createdBy": null,
          "updatedBy": null,
          "createdTimestamp": null,
          "updatedTimestamp": null,
          "validFrom": null,
          "validTo": null,
          "tenantId": null,
          "uuid": null,
          "date": "2022-12-01T00:00:00.000+00:00",
          "openingBalance": 126897.67,
          "closingBalance": 126897.67,
          "closingAvailableBalance": null,
          "forwardedBalance": 0.0,
          "accountNumber": "601320369201",
          "accountCurrency": "USD",
          "statementNumber": "00277",
          "transactionReferenceNumber": "2212010010181731",
          "relatedReference": "",
          "infoToAccOwner": null,
          "trailer": null,
          "transactionList": null
        }
      ]
    },
    {
      "accountNumber": null,
      "fileName": "Framework Walk Through - Attendance report 25-11-22.csv",
      "parseStatus": false,
      "statementList": null
    }
  ];

}
